version: "3"

services:
  db:
    image: mongo
    container_name: mongo_container
    command: mongod --auth
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=falcon_mongo
      - MONGO_INITDB_ROOT_USERNAME=falcon_db
      - MONGO_INITDB_ROOT_PASSWORD=6783
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb_data:/data/db
      - ./mongodb_init/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  falcon:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /falcon
          ignore:
            - node_modules/
            - yarn.lock
            - package-lock.json
            - data
            - package.json
        - action: rebuild
          path: package.json
    volumes:
      - ./data/backend:/falcon/data/app:rw
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  db:
    driver: local
  falcon:
    driver: local