version: "3"

services:
  db:
    image: mysql
    restart: on-failure
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 6783
    volumes:
      - ./data/mysqlDB:/var/lib/mysql
      - ./mysql_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  falcon:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/falcon:rw

volumes:
  db:
    driver: local
  falcon:
    driver: local